# Generated by Django 5.0.4 on 2024-04-27 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='racers',
        ),
        migrations.AddField(
            model_name='race',
            name='racers',
            field=models.ManyToManyField(blank=True, through='races.RaceEntry', to=settings.AUTH_USER_MODEL),
        ),
    ]
