# Generated by Django 5.0.4 on 2024-04-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_alter_race_racers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceentry',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
