# Generated by Django 5.0.3 on 2024-04-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_alter_race_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='date_of_completion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
