# Generated by Django 5.0.3 on 2024-04-09 23:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_alter_race_date_of_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
