# Generated by Django 5.0.3 on 2024-04-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_race_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
