# Generated by Django 5.0.3 on 2024-04-10 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_race_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='date',
        ),
    ]
