# Generated by Django 5.0.4 on 2024-05-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_rename_position_raceentry_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceentry',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
