# Generated by Django 5.0.4 on 2024-05-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_raceentry_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceentry',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
