# Generated by Django 5.0.3 on 2024-04-11 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_remove_race_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='date_of_completion',
            new_name='completion_date',
        ),
        migrations.RemoveField(
            model_name='race',
            name='is_completed',
        ),
    ]
