# Generated by Django 5.0.4 on 2024-04-16 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0007_rename_date_of_completion_race_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['-pk']},
        ),
    ]
