# Generated by Django 5.0.3 on 2024-03-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='racer',
            name='slug',
        ),
        migrations.AddField(
            model_name='racer',
            name='loses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='racer',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racer',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='racer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='racer',
            name='sponsors',
            field=models.ManyToManyField(to='racers.sponsor'),
        ),
    ]
