# Generated by Django 5.0.4 on 2024-05-02 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racer',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='racer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
