# Generated by Django 5.0.3 on 2024-03-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0002_sponsor_remove_racer_slug_racer_loses_racer_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='sponsors',
            field=models.ManyToManyField(blank=True, null=True, to='racers.sponsor'),
        ),
    ]
