# Generated by Django 5.0.4 on 2024-05-02 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0002_remove_racer_car_car_racer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
