# Generated by Django 5.0.3 on 2024-03-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0003_alter_racer_sponsors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='racers.sponsor'),
        ),
    ]
