# Generated by Django 5.0.4 on 2024-05-07 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0004_racer_active_since_racer_stance_racer_year_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='racer',
            name='year_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
