# Generated by Django 5.0.3 on 2024-03-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0004_alter_racer_sponsors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
