# Generated by Django 5.0.3 on 2024-03-22 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0005_alter_racer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racer',
            name='number',
        ),
    ]
