# Generated by Django 5.0.3 on 2024-03-28 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0006_remove_racer_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=75)),
                ('speed', models.IntegerField()),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.RemoveField(
            model_name='racer',
            name='sponsors',
        ),
        migrations.AddField(
            model_name='racer',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='racer',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='racer',
            name='second_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='racer',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='racers.car'),
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
