# Generated by Django 5.0.4 on 2024-05-12 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0007_alter_racer_active_since'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racer',
            name='active_since',
        ),
    ]
