# Generated by Django 5.0.3 on 2024-03-28 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0007_car_remove_racer_sponsors_racer_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='number',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
        ),
    ]
