# Generated by Django 5.0.3 on 2024-04-09 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0008_alter_racer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
        ),
    ]
