# Generated by Django 5.0.4 on 2024-04-16 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0009_alter_racer_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='racer',
            options={'ordering': ['-pk']},
        ),
    ]
