# Generated by Django 5.0.4 on 2024-04-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0010_alter_racer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racer',
            name='loses',
        ),
        migrations.RemoveField(
            model_name='racer',
            name='wins',
        ),
        migrations.AddField(
            model_name='racer',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
