# Generated by Django 5.0.4 on 2024-04-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0012_alter_racer_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
