# Generated by Django 5.0.4 on 2024-05-10 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_options_alter_carmodel_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='year',
            new_name='date_of_manufacture',
        ),
    ]
